from __future__ import annotations


def build_lab_test_config(theory_mode: str = "qm_free") -> dict[str, object]:
    return {
        "simulation": {
            "grid_size": 21,
            "steps": 12,
            "t_max_steps": 12,
            "dt": 0.2,
            "hopping": 1.0,
            "initial_site": "center",
            "feedback_smoothing": 1.0,
            "fit_start_step": 2,
            "fit_end_step": None,
            "validation_tolerance": 1.0e-12,
        },
        "parameters": {
            "W": 3.2,
            "bias": 0.0,
            "eta": 0.6,
            "gamma": 0.08,
            "seed": 7,
        },
        "montecarlo": {
            "runs": 4,
            "base_seed": 100,
            "vary": {"W_std": 0.1, "bias_std": 0.01, "eta_std": 0.05, "gamma_std": 0.01},
        },
        "sweep": {
            "W_values": [0.0, 1.0],
            "bias_values": [0.0],
            "eta_values": [0.0, 0.4],
            "gamma_values": [0.0],
            "phase_map_axes": ["W", "eta"],
            "phase_metric": "alpha",
            "phase_valid_only": True,
            "boundary_detection": {"high_alpha_threshold": 0.8, "low_alpha_threshold": 0.2},
        },
        "hunter": {
            "target_alpha": 0.5,
            "rounds": 2,
            "samples_per_round": 4,
            "shrink_factor": 0.5,
            "search_center": {"W": 1.0, "bias": 0.05, "eta": 0.3, "gamma": 0.0},
            "search_span": {"W": 0.5, "bias": 0.05, "eta": 0.3, "gamma": 0.0},
        },
        "inverse_analysis": {
            "path_axis": "W",
            "slice_keys": ["bias", "eta", "gamma"],
            "dominance_threshold": 0.25,
            "annihilation_threshold": 0.90,
        },
        "audit": {
            "diffusive_alpha_target": 0.5,
            "diffusive_alpha_tolerance": 0.035,
            "min_r2": 0.95,
            "max_unitarity_error": 1.0e-12,
            "max_hermitian_error": 1.0e-12,
            "required_gamma": 0.0,
            "max_alpha_window_shift": 0.05,
            "top_n": 20,
        },
        "lab": {
            "theory_mode": theory_mode,
            "grid_size": 33,
            "time_horizon_steps": 24,
            "dt": 0.15,
            "hopping": 1.0,
            "W": 3.0,
            "bias": 0.0,
            "eta": 0.5,
            "gamma": 0.10,
            "seed": 11,
            "feedback_smoothing": 1.0,
            "burn_in_fraction": 0.4,
            "falldown_variance_epsilon": 2.0,
            "falldown_velocity_min": 0.02,
            "edge_threshold": 0.05,
            "trace_tolerance": 1.0e-6,
            "rtt_stagnation_window": 4,
            "rtt_transport_epsilon": 1.0e-3,
            "rtt_adaptive_strength": 0.15,
            "edge_width": 4,
            "frame_corr_threshold": 0.995,
            "experimental": True,
            "topology_policy": None,
            "audit_feedback": "logged_only",
            "wave_packet": {"x0": 10, "sigma": 2.5, "k0": 0.55},
            "render": {"animate": False, "fps": 12},
        },
    }
